"""empty message

Revision ID: b2f313a0e02f
Revises: 
Create Date: 2021-04-29 11:40:08.781134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f313a0e02f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profile', sa.Column('level', sa.String(length=10), nullable=False))
    op.drop_column('student_profile', 'programme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profile', sa.Column('programme', sa.VARCHAR(length=300), nullable=False))
    op.drop_column('student_profile', 'level')
    # ### end Alembic commands ###
